# Docker compose file shared storage and network
version: "3.4"

services:
  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql
    restart: always
    volumes:
      - type: volume
        source: wordpress_files
        target: /var/www/html
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_pass
      WORDPRESS_DB_NAME: wordpress

  mysql:
    image: mysql:5.7
    volumes:
      - type: volume
        source: db_vol
        target: /var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress_root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_pass

networks:
  default:
    external:
      name: custom_network

volumes:
  db_vol:
    external: true
  wordpress_files:
    external: true
