## Docker composer V1
version: "3.4"

services:

  wordpress:
    depends_on: 
      - mysql
    image: wordpress:latest
    volumes:
      - type: volume
        source: wordpress_files
        target: /var/www/html
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_pass
      WORDPRESS_DB_NAME: wordpress

  mysql:
    image: mysql:5.7
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress_root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_pass

volumes:
  db_data:
  wordpress_files:
